---

- hosts: all
  become: true
  tasks:

  - name: Update repository index (RH/CentOS)
    dnf:
      update_cache: yes 
    when: ansible_facts["os_family"] == "RedHat" 

  - name: Install the apache2 package (RH/CentOS)
    ansible.builtin.dnf: 
      name: httpd
      state: latest
    when: ansible_facts["os_family"] == "RedHat"

  - name: add php support for apache (RH/CentOS)
    dnf:
      name: php-fpm
    when: ansible_facts["os_family"] == "RedHat"
  
  - name: add support for apache (Ubuntu)
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_facts["os_family"] == "Ubuntu" 

  - name: Install Apache2 package (Ubuntu)
    apt:
      name: apache2
      state: latest
    when: ansible_facts["os_family"] == "Ubuntu"   
