---

- hosts: all
  become: true
  tasks:

  - name: Update repository index
    dnf:
      update_cache: yes  

  - name: Install the apache2 package
    ansible.builtin.dnf: 
      name: httpd
      state: latest

  - name: add php support for apache
    dnf:
      name: php-fpm
