---

- hosts: all
  become: true
  tasks:

  - name: Install updates (centOS)
    dnf:
      name: "*"
      state: latest
      update_only: yes
      update_cache: yes
    when: ansible_facts["os_family"] == "RedHat"
 
  - name: Install updates Ubuntu
    apt:
      update_only: yes
      upgrade: dist
    when: ansible_facts["os_family"] == "Debian"

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - php
      state: latest
    when: ansible_facts["distribution"] == "Ubuntu"

  - name: Install apache and php for CentOS/RedHat servers
    dnf:
      name:
       - httpd
       - php-ftp
      state: latest
    when: ansible_facts["os_family"] == "RedHat"

- hosts: db_servers
  become: true
  tasks:

  - name: Istall mariadb package (RedHat)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_facts["os_family"] == "RedHat"

  - name: Install mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_facts["distribution"] == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    package:
      name: samba
      state: latest

