---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (centOS)
    tags: always
    dnf:
      name: "*"
      state: latest
      update_only: yes
      update_cache: yes
    when: ansible_facts["os_family"] == "RedHat"
 
  - name: Install updates Ubuntu
    tags: always
    apt:
      update_only: yes
      upgrade: dist
    when: ansible_facts["os_family"] == "Debian"

- hosts: workstations
  become: true
  tasks:

  - name: Install unzip
    package:
      name: unzip

  - name: Install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.14.8/terraform_1.14.8_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - php
      state: latest
    when: ansible_facts["distribution"] == "Ubuntu"

  - name: Copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
    register: httpd

  - name: Install apache and php for CentOS/RedHat servers
    tags: apache,apache2,ubuntu
    dnf:
      name:
       - httpd
       - php-ftp
      state: latest
    when: ansible_facts["os_family"] == "RedHat"

  - name: Start httpd (CentOS)
    tags: centos,httpd,apache
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_facts["os_family"] == "RedHat"

  - name: Restart httpd (centos)
    tags: centos,apache,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed


- hosts: db_servers
  become: true
  tasks:

  - name: Install mariadb package (RedHat)
    tags: db,mariadb,centos
    dnf: 
      name: mariadb
      state: latest
    when: ansible_facts["os_family"] == "RedHat"

  - name: Install mariadb package (Ubuntu)
    tags: db,mariadb,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_facts["distribution"] == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: Install samba package
    tags: samba
    package:
      name: samba
      state: latest

